[package]
name = "ovsdb-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.0", features = ["serde"] } 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
