[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ovsdb-schema = { path = "../../crates/ovsdb-schema" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.2", features = ["derive"] }
